version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: andrei
      MONGO_INITDB_ROOT_PASSWORD: nHZtFji3qPejxVLyzGVJaejX
    volumes:
      - /Users/andrei/Docker/mongo:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: andrei
      ME_CONFIG_MONGODB_ADMINPASSWORD: nHZtFji3qPejxVLyzGVJaejX
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_URL: mongodb://andrei:nHZtFji3qPejxVLyzGVJaejX@mongo:27017/

  bukemes-back:
    image: elfensky/bukemes-back:dev
    # restart: always
    ports:
      - 9001:9001
    environment:
      MONGO_USER: andrei
      MONGO_PASSWORD: nHZtFji3qPejxVLyzGVJaejX
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: testDB
      MONGO_AUTH_SOURCE: admin